/* Generated By:JavaCC: Do not edit this line. FunConstants.java */
package parser;

public interface FunConstants {

  int EOF = 0;
  int BREAK = 6;
  int CLASS = 7;
  int CONSTRUCTOR = 8;
  int ELSE = 9;
  int EXTENDS = 10;
  int FOR = 11;
  int IF = 12;
  int INT = 13;
  int NEW = 14;
  int PRINT = 15;
  int READ = 16;
  int RETURN = 17;
  int STRING = 18;
  int SUPER = 19;
  int FLOAT = 20;
  int CHAR = 21;
  int BOOLEAN = 22;
  int PLUS = 23;
  int MINUS = 24;
  int MULTIPLY = 25;
  int DIVIDE = 26;
  int REM = 27;
  int ASSIGN = 28;
  int GT = 29;
  int LT = 30;
  int EQ = 31;
  int LE = 32;
  int GE = 33;
  int NEQ = 34;
  int NOT = 35;
  int AND = 36;
  int XOR = 37;
  int OR = 38;
  int LPAREN = 39;
  int RPAREN = 40;
  int LBRACE = 41;
  int RBRACE = 42;
  int LBRACKET = 43;
  int RBRACKET = 44;
  int SEMICOLON = 45;
  int COMMA = 46;
  int DOT = 47;
  int int_constant = 48;
  int string_constant = 49;
  int char_constant = 50;
  int float_constant = 51;
  int boolean_constant = 52;
  int null_constant = 53;
  int IDENT = 54;
  int LETTER = 55;
  int DIGIT = 56;
  int INVALID_LEXICAL = 63;
  int INVALID_CHAR_CONST = 64;
  int INVALID_STRING_CONST = 65;

  int DEFAULT = 0;
  int multilinecomment = 1;
  int singlelinecommnet = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"break\"",
    "\"class\"",
    "\"constructor\"",
    "\"else\"",
    "\"extends\"",
    "\"for\"",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"print\"",
    "\"read\"",
    "\"return\"",
    "\"string\"",
    "\"super\"",
    "\"float\"",
    "\"char\"",
    "\"boolean\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"not\"",
    "\"and\"",
    "\"xor\"",
    "\"or\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "<int_constant>",
    "<string_constant>",
    "<char_constant>",
    "<float_constant>",
    "<boolean_constant>",
    "\"null\"",
    "<IDENT>",
    "<LETTER>",
    "<DIGIT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 59>",
    "\"//\"",
    "<token of kind 61>",
    "<token of kind 62>",
    "<INVALID_LEXICAL>",
    "<INVALID_CHAR_CONST>",
    "<INVALID_STRING_CONST>",
  };

}
